# https://taskfile.dev

version: '3'

tasks:

  commit:
    cmds:
      - git add .
      - git commit -m "Updated mappings"

  gofmt:
    dir: pkg/webview2
    cmds:
      - go fmt

  test:
    cmds:
      - go test ./...

  update:
    dir: scripts
    cmds:
      - go run update_version_mapping.go
      - task: gofmt
      - go fmt update_version_mapping.go
      - task: test
      - task: commit

  update:forced:
    dir: scripts
    cmds:
      - go run update_version_mapping.go -forced
      - task: gofmt
      - go fmt update_version_mapping.go
      - task: test
      - task: commit
